name: CI
on:
  push:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true
          version: latest
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - uses: JonasKruckenberg/tauri-build@v1
        id: tauri_build
      # - name: Compress binaries
      #   if: matrix.platform == 'ubuntu-latest'
      #   uses: svenstaro/upx-action@v2
      #   with:
      #     file: build/bin/smart-tool.exe
      #     args: -9 -o build/bin/smart-tool-upx.exe
      #     strip: false
      # - name: Compress binaries
      #   if: matrix.platform == 'macos-latest'
      #   uses: svenstaro/upx-action@v2
      #   with:
      #     file: build/bin/smart-tool.exe
      #     args: -9 -o build/bin/smart-tool-upx.exe
      #     strip: false
      # - name: Compress binaries
      #   if: matrix.platform == 'windows-latest'
      #   uses: svenstaro/upx-action@v2
      #   with:
      #     file: build/bin/smart-tool.exe
      #     args: -9 -o build/bin/smart-tool-upx.exe
      #     strip: false
      # The `artifacts` output can now be used by a different action to upload the artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: "${{ join(fromJSON(steps.tauri_build.outputs.artifacts), '\n') }}"
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     body: 带upx后缀的是经过压缩的启动器，如果缺少运行时可以到微软官网下载：[webview2](https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section)
      #     files: |
      #       build/bin/smart-tool.exe
      #       build/bin/smart-tool-upx.exe
